name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Installation

  The Third Coast `vendordeps` file is at: http://packages.strykeforce.org/thirdcoast.json

  To install, use **Install new libraries (online)** in VS Code or download manually to your project `vendordeps` directory.

  ```
  $ ./gradlew vendordep --url=http://packages.strykeforce.org/thirdcoast.json
  ```

  ## Changes

  $CHANGES
